# fenez/materials_lookup.py

material_lookup = {
    "Concrete_200mm": {
        "obj_type": "MATERIAL",
        "Name": "Concrete_200mm",
        "Roughness": "MediumRough",
        "Thickness_range": (0.195, 0.205),
        "Conductivity_range": (1.5, 1.7),
        "Density_range": (2250, 2350),
        "Specific_Heat_range": (850, 950),
        "Thermal_Absorptance_range": (0.9, 0.9),
        "Solar_Absorptance_range": (0.7, 0.7),
        "Visible_Absorptance_range": (0.7, 0.7)
    },
    "InsulationBoard_R2": {
        "obj_type": "MATERIAL:NOMASS",
        "Name": "InsulationBoard_R2",
        "Roughness": "MediumRough",
        "Thermal_Resistance_range": (0.34, 0.36),
        "Thermal_Absorptance_range": (0.9, 0.9),
        "Solar_Absorptance_range": (0.7, 0.7),
        "Visible_Absorptance_range": (0.7, 0.7)
    },
    "Glazing_Clear_3mm": {
        "obj_type": "WINDOWMATERIAL:GLAZING",
        "Name": "Glazing_Clear_3mm",
        "Optical_Data_Type": "SpectralAverage",
        "Thickness_range": (0.003, 0.003),
        "Solar_Transmittance_range": (0.76, 0.78),
        "Front_Solar_Reflectance_range": (0.07, 0.08),
        "Back_Solar_Reflectance_range": (0.07, 0.08),
        "Visible_Transmittance_range": (0.86, 0.88),
        "Front_Visible_Reflectance_range": (0.06, 0.07),
        "Back_Visible_Reflectance_range": (0.06, 0.07),
        "IR_Transmittance": 0.0,
        "Front_IR_Emissivity_range": (0.84, 0.84),
        "Back_IR_Emissivity_range": (0.84, 0.84),
        "Conductivity_range": (0.95, 1.05),
        "Dirt_Correction_Factor_range": (1.0, 1.0),
        "Solar_Diffusing": "No"
    },
    "Glazing_Clear_3mm_Post": {
        "obj_type": "WINDOWMATERIAL:GLAZING",
        "Name": "Glazing_Clear_3mm_Post",
        "Optical_Data_Type": "SpectralAverage",
        "Thickness_range": (0.003, 0.003),
        "Solar_Transmittance_range": (0.75, 0.75),
        "Front_Solar_Reflectance_range": (0.07, 0.07),
        "Back_Solar_Reflectance_range": (0.07, 0.07),
        "Visible_Transmittance_range": (0.85, 0.85),
        "Front_Visible_Reflectance_range": (0.07, 0.07),
        "Back_Visible_Reflectance_range": (0.07, 0.07),
        "IR_Transmittance": 0.0,
        "Front_IR_Emissivity_range": (0.84, 0.84),
        "Back_IR_Emissivity_range": (0.84, 0.84),
        "Conductivity_range": (1.0, 1.0),
        "Dirt_Correction_Factor_range": (1.0, 1.0),
        "Solar_Diffusing": "No"
    },
    "DoorPanel_Range": {
        "obj_type": "MATERIAL",
        "Name": "DoorPanel_Range",
        "Roughness": "MediumSmooth",
        "Thickness_range": (0.04, 0.05),
        "Conductivity_range": (0.4, 0.5),
        "Density_range": (600, 700),
        "Specific_Heat_range": (1200, 1300),
        "Thermal_Absorptance_range": (0.9, 0.9),
        "Solar_Absorptance_range": (0.7, 0.7),
        "Visible_Absorptance_range": (0.7, 0.7)
    },
    "Ceiling_Insulation_R3": {
        "obj_type": "MATERIAL",
        "Name": "Ceiling_Insulation_R3",
        "Roughness": "MediumRough",
        "Thickness_range": (0.02, 0.03),
        "Conductivity_range": (0.035, 0.045),
        "Density_range": (20, 25),
        "Specific_Heat_range": (1400, 1500),
        "Thermal_Absorptance_range": (0.9, 0.9),
        "Solar_Absorptance_range": (0.7, 0.7),
        "Visible_Absorptance_range": (0.7, 0.7)
    },
    "Roof_Insulation_R5": {
        "obj_type": "MATERIAL",
        "Name": "Roof_Insulation_R5",
        "Roughness": "MediumRough",
        "Thickness_range": (0.04, 0.05),
        "Conductivity_range": (0.03, 0.04),
        "Density_range": (25, 30),
        "Specific_Heat_range": (1400, 1500),
        "Thermal_Absorptance_range": (0.9, 0.9),
        "Solar_Absorptance_range": (0.7, 0.7),
        "Visible_Absorptance_range": (0.7, 0.7)
    },
    "AdiabaticWall_Generic": {
        "obj_type": "MATERIAL",
        "Name": "AdiabaticWall_Generic",
        "Roughness": "MediumSmooth",
        "Thickness_range": (0.15, 0.20),
        "Conductivity_range": (0.30, 0.40),
        "Density_range": (200, 300),
        "Specific_Heat_range": (1000, 1100),
        "Thermal_Absorptance_range": (0.9, 0.9),
        "Solar_Absorptance_range": (0.7, 0.7),
        "Visible_Absorptance_range": (0.7, 0.7)
    },
    "GroundContactFloor_Generic": {
        "obj_type": "MATERIAL",
        "Name": "GroundContactFloor_Generic",
        "Roughness": "MediumRough",
        "Thickness_range": (0.10, 0.12),
        "Conductivity_range": (1.0, 1.2),
        "Density_range": (2100, 2300),
        "Specific_Heat_range": (850, 900),
        "Thermal_Absorptance_range": (0.9, 0.9),
        "Solar_Absorptance_range": (0.7, 0.7),
        "Visible_Absorptance_range": (0.7, 0.7)
    },
}
