residential_materials_data = {
    ('Accommodation Function', '2006-2014', 'scenario1', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 7.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (2.5, 3.4),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 45.0,
            "R_value_range": (0.2, 0.4),
            "U_value_range": (2.5, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 55.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (1.8, 2.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 90.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (1.5, 2.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 28.0,
            "R_value_range": (0.05, 0.3),
            "U_value_range": (1.8, 2.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Accommodation Function', '2006-2014', 'scenario1', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 7.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (2.5, 3.4),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 45.0,
            "R_value_range": (0.2, 0.4),
            "U_value_range": (2.5, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 55.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (1.8, 2.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 90.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (1.5, 2.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 28.0,
            "R_value_range": (0.05, 0.3),
            "U_value_range": (1.8, 2.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Accommodation Function', '2006-2014', 'scenario2', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 7.0,
            "R_value_range": (0.1, 0.3),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 45.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (2.0, 2.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 55.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (1.6, 2.2),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 90.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (1.3, 1.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 28.0,
            "R_value_range": (0.08, 0.25),
            "U_value_range": (1.6, 2.2),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Accommodation Function', '2006-2014', 'scenario2', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 7.0,
            "R_value_range": (0.1, 0.3),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 45.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (2.0, 2.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 55.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (1.6, 2.2),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 90.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (1.3, 1.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 28.0,
            "R_value_range": (0.08, 0.25),
            "U_value_range": (1.6, 2.2),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Cell Function', '2006-2014', 'scenario1', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 6.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 40.0,
            "R_value_range": (0.2, 0.4),
            "U_value_range": (2.5, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 50.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (1.8, 2.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 80.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (1.5, 2.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 25.0,
            "R_value_range": (0.05, 0.3),
            "U_value_range": (1.8, 2.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Cell Function', '2006-2014', 'scenario1', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 6.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 40.0,
            "R_value_range": (0.2, 0.4),
            "U_value_range": (2.5, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 50.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (1.8, 2.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 80.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (1.5, 2.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 25.0,
            "R_value_range": (0.05, 0.3),
            "U_value_range": (1.8, 2.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Cell Function', '2006-2014', 'scenario2', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 6.0,
            "R_value_range": (0.1, 0.3),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 40.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (2.0, 2.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 50.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (1.6, 2.2),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 80.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (1.3, 1.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 25.0,
            "R_value_range": (0.08, 0.25),
            "U_value_range": (1.6, 2.2),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Cell Function', '2006-2014', 'scenario2', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 6.0,
            "R_value_range": (0.1, 0.3),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 40.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (2.0, 2.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 50.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (1.6, 2.2),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 80.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (1.3, 1.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 25.0,
            "R_value_range": (0.08, 0.25),
            "U_value_range": (1.6, 2.2),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Education Function', '1992-2005', 'scenario1', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 11.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (3.8, 5.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 65.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (3.8, 4.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 75.0,
            "R_value_range": (0.35, 0.7),
            "U_value_range": (2.2, 3.2),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 140.0,
            "R_value_range": (0.4, 0.8),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 50.0,
            "R_value_range": (0.1, 0.35),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Education Function', '1992-2005', 'scenario1', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 11.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (3.8, 5.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 65.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (3.8, 4.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 75.0,
            "R_value_range": (0.35, 0.7),
            "U_value_range": (2.2, 3.2),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 140.0,
            "R_value_range": (0.4, 0.8),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 50.0,
            "R_value_range": (0.1, 0.35),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Education Function', '1992-2005', 'scenario2', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 11.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (3.5, 4.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 65.0,
            "R_value_range": (0.25, 0.55),
            "U_value_range": (3.5, 4.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 75.0,
            "R_value_range": (0.3, 0.65),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 140.0,
            "R_value_range": (0.35, 0.7),
            "U_value_range": (2.8, 3.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 50.0,
            "R_value_range": (0.08, 0.3),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Education Function', '1992-2005', 'scenario2', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 11.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (3.5, 4.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 65.0,
            "R_value_range": (0.25, 0.55),
            "U_value_range": (3.5, 4.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 75.0,
            "R_value_range": (0.3, 0.65),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 140.0,
            "R_value_range": (0.35, 0.7),
            "U_value_range": (2.8, 3.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 50.0,
            "R_value_range": (0.08, 0.3),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Healthcare Function', '2006-2014', 'scenario1', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 10.0,
            "R_value_range": (0.2, 0.4),
            "U_value_range": (3.0, 4.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 70.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 80.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 120.0,
            "R_value_range": (0.35, 0.7),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 40.0,
            "R_value_range": (0.08, 0.3),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Healthcare Function', '2006-2014', 'scenario1', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 10.0,
            "R_value_range": (0.2, 0.4),
            "U_value_range": (3.0, 4.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 70.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 80.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 120.0,
            "R_value_range": (0.35, 0.7),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 40.0,
            "R_value_range": (0.08, 0.3),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Healthcare Function', '2006-2014', 'scenario2', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 10.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (2.5, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 70.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 80.0,
            "R_value_range": (0.25, 0.55),
            "U_value_range": (1.8, 2.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 120.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 40.0,
            "R_value_range": (0.05, 0.25),
            "U_value_range": (1.8, 2.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Healthcare Function', '2006-2014', 'scenario2', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 10.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (2.5, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 70.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 80.0,
            "R_value_range": (0.25, 0.55),
            "U_value_range": (1.8, 2.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 120.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 40.0,
            "R_value_range": (0.05, 0.25),
            "U_value_range": (1.8, 2.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Industrial Function', '2015-2018', 'scenario1', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 15.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (4.0, 5.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 100.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (4.0, 5.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 120.0,
            "R_value_range": (0.35, 0.7),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 200.0,
            "R_value_range": (0.4, 0.8),
            "U_value_range": (3.5, 4.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 60.0,
            "R_value_range": (0.1, 0.35),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Industrial Function', '2015-2018', 'scenario1', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 15.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (4.0, 5.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 100.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (4.0, 5.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 120.0,
            "R_value_range": (0.35, 0.7),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 200.0,
            "R_value_range": (0.4, 0.8),
            "U_value_range": (3.5, 4.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 60.0,
            "R_value_range": (0.1, 0.35),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Industrial Function', '2015-2018', 'scenario2', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 15.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (3.5, 4.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 100.0,
            "R_value_range": (0.25, 0.55),
            "U_value_range": (3.5, 4.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 120.0,
            "R_value_range": (0.3, 0.65),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 200.0,
            "R_value_range": (0.35, 0.7),
            "U_value_range": (2.8, 3.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 60.0,
            "R_value_range": (0.08, 0.3),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Industrial Function', '2015-2018', 'scenario2', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 15.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (3.5, 4.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 100.0,
            "R_value_range": (0.25, 0.55),
            "U_value_range": (3.5, 4.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 120.0,
            "R_value_range": (0.3, 0.65),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 200.0,
            "R_value_range": (0.35, 0.7),
            "U_value_range": (2.8, 3.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 60.0,
            "R_value_range": (0.08, 0.3),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Meeting Function', '2006-2014', 'scenario1', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.3, 0.35),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 8.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "DoorPanel_Range",
            "material_window_lookup": "Glazing_Clear_3mm",
        },
        "ground_floor": {
            "area_m2": 50.0,
            "R_value_range": (0.2, 0.4),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 60.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (1.8, 2.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 100.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (1.5, 2.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 30.0,
            "R_value_range": (0.05, 0.3),
            "U_value_range": (1.8, 2.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Meeting Function', '2006-2014', 'scenario1', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.3, 0.35),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 8.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "DoorPanel_Range",
            "material_window_lookup": "Glazing_Clear_3mm",
        },
        "ground_floor": {
            "area_m2": 50.0,
            "R_value_range": (0.2, 0.4),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 60.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (1.8, 2.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 100.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (1.5, 2.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 30.0,
            "R_value_range": (0.05, 0.3),
            "U_value_range": (1.8, 2.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Meeting Function', '2006-2014', 'scenario2', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 8.0,
            "R_value_range": (0.1, 0.3),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 50.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (2.0, 2.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 60.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (1.6, 2.2),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 100.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (1.3, 1.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 30.0,
            "R_value_range": (0.08, 0.25),
            "U_value_range": (1.6, 2.2),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Meeting Function', '2006-2014', 'scenario2', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 8.0,
            "R_value_range": (0.1, 0.3),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 50.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (2.0, 2.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 60.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (1.6, 2.2),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 100.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (1.3, 1.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 30.0,
            "R_value_range": (0.08, 0.25),
            "U_value_range": (1.6, 2.2),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Office Function', '2015-2018', 'scenario1', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 9.0,
            "R_value_range": (0.2, 0.4),
            "U_value_range": (3.5, 4.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 80.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (3.5, 4.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 90.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 160.0,
            "R_value_range": (0.35, 0.7),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 45.0,
            "R_value_range": (0.05, 0.3),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Office Function', '2015-2018', 'scenario1', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 9.0,
            "R_value_range": (0.2, 0.4),
            "U_value_range": (3.5, 4.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 80.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (3.5, 4.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 90.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 160.0,
            "R_value_range": (0.35, 0.7),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 45.0,
            "R_value_range": (0.05, 0.3),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Office Function', '2015-2018', 'scenario2', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 9.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 80.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 90.0,
            "R_value_range": (0.25, 0.55),
            "U_value_range": (1.8, 2.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 160.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 45.0,
            "R_value_range": (0.08, 0.25),
            "U_value_range": (1.8, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Office Function', '2015-2018', 'scenario2', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 9.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 80.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 90.0,
            "R_value_range": (0.25, 0.55),
            "U_value_range": (1.8, 2.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 160.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 45.0,
            "R_value_range": (0.08, 0.25),
            "U_value_range": (1.8, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Other Use Function', '2006-2014', 'scenario1', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 5.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 35.0,
            "R_value_range": (0.2, 0.4),
            "U_value_range": (2.5, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 45.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (1.8, 2.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 70.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (1.5, 2.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 20.0,
            "R_value_range": (0.05, 0.3),
            "U_value_range": (1.8, 2.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Other Use Function', '2006-2014', 'scenario1', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 5.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 35.0,
            "R_value_range": (0.2, 0.4),
            "U_value_range": (2.5, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 45.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (1.8, 2.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 70.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (1.5, 2.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 20.0,
            "R_value_range": (0.05, 0.3),
            "U_value_range": (1.8, 2.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Other Use Function', '2006-2014', 'scenario2', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 5.0,
            "R_value_range": (0.1, 0.3),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 35.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (2.0, 2.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 45.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (1.6, 2.2),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 70.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (1.3, 1.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 20.0,
            "R_value_range": (0.08, 0.25),
            "U_value_range": (1.6, 2.2),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Other Use Function', '2006-2014', 'scenario2', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 5.0,
            "R_value_range": (0.1, 0.3),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 35.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (2.0, 2.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 45.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (1.6, 2.2),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 70.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (1.3, 1.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 20.0,
            "R_value_range": (0.08, 0.25),
            "U_value_range": (1.6, 2.2),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Retail Function', '2006-2014', 'scenario1', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 10.0,
            "R_value_range": (0.2, 0.4),
            "U_value_range": (3.0, 4.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 60.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 70.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (1.8, 2.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 130.0,
            "R_value_range": (0.35, 0.7),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 35.0,
            "R_value_range": (0.05, 0.3),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Retail Function', '2006-2014', 'scenario1', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 10.0,
            "R_value_range": (0.2, 0.4),
            "U_value_range": (3.0, 4.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 60.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 70.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (1.8, 2.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 130.0,
            "R_value_range": (0.35, 0.7),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 35.0,
            "R_value_range": (0.05, 0.3),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Retail Function', '2006-2014', 'scenario2', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 10.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (2.5, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 60.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 70.0,
            "R_value_range": (0.25, 0.55),
            "U_value_range": (1.6, 2.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 130.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 35.0,
            "R_value_range": (0.08, 0.25),
            "U_value_range": (1.8, 2.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Retail Function', '2006-2014', 'scenario2', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 10.0,
            "R_value_range": (0.15, 0.35),
            "U_value_range": (2.5, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 60.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 70.0,
            "R_value_range": (0.25, 0.55),
            "U_value_range": (1.6, 2.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 130.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 35.0,
            "R_value_range": (0.08, 0.25),
            "U_value_range": (1.8, 2.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Sport Function', '2015-2018', 'scenario1', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 12.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (4.0, 5.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 90.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (3.5, 4.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 100.0,
            "R_value_range": (0.35, 0.7),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 150.0,
            "R_value_range": (0.4, 0.8),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 50.0,
            "R_value_range": (0.1, 0.35),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Sport Function', '2015-2018', 'scenario1', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 12.0,
            "R_value_range": (0.25, 0.5),
            "U_value_range": (4.0, 5.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 90.0,
            "R_value_range": (0.3, 0.6),
            "U_value_range": (3.5, 4.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 100.0,
            "R_value_range": (0.35, 0.7),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 150.0,
            "R_value_range": (0.4, 0.8),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 50.0,
            "R_value_range": (0.1, 0.35),
            "U_value_range": (2.5, 3.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Sport Function', '2015-2018', 'scenario2', 'post_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 12.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (3.5, 4.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 90.0,
            "R_value_range": (0.25, 0.55),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 100.0,
            "R_value_range": (0.3, 0.65),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 150.0,
            "R_value_range": (0.35, 0.7),
            "U_value_range": (2.8, 3.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 50.0,
            "R_value_range": (0.08, 0.3),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

    ('Sport Function', '2015-2018', 'scenario2', 'pre_calibration'): {
        "roughness": "MediumRough",
        "wwr_range": (0.32, 0.36),
        "material_opaque_lookup": "Concrete_200mm",
        "material_window_lookup": "Glazing_Clear_3mm_Post",
        "doors": {
            "area_m2": 12.0,
            "R_value_range": (0.2, 0.45),
            "U_value_range": (3.5, 4.5),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "ground_floor": {
            "area_m2": 90.0,
            "R_value_range": (0.25, 0.55),
            "U_value_range": (3.0, 4.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "sloping_flat_roof": {
            "area_m2": 100.0,
            "R_value_range": (0.3, 0.65),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "solid_wall": {
            "area_m2": 150.0,
            "R_value_range": (0.35, 0.7),
            "U_value_range": (2.8, 3.8),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
        "windows": {
            "area_m2": 50.0,
            "R_value_range": (0.08, 0.3),
            "U_value_range": (2.0, 3.0),
            "material_opaque_lookup": "Concrete_200mm",
            "material_window_lookup": "Glazing_Clear_3mm_Post",
        },
    },

}
